# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee3e7aaa1bb5f090a8e3d7c0a989c87d3082819a3eb2cdc57c4f312d7485bd855b6e518f85031df4785a094eff6c68c9ba6535a032f4012e06c674005c8e809a

test:
  secret_key_base: 72cd519d4aa6607fce1ef8e35f0c95ec6e1eba691af7277f18c7907273443cac550fc8e0c95f6377d827f7f40fecce367169b6410c51ff21b6b908cb8d49a3a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
